version: '3.8'
services:
    mariadb:
        container_name: database
        image: mariadb:10.6
        restart: 'always'
        ports:
            - "127.0.0.1:3306:3306"
        volumes:
            - ./config/initdb:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        links:
            - mariadb
        environment:
            PMA_HOST: mariadb
            PMA_PORT: 3306
            PMA_USER: ${MYSQL_USER}
            PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            UPLOAD_LIMIT: 512M
            MEMORY_LIMIT: 512M
        ports:
            - '8080:80'
        volumes:
            - ./config/php/php.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    php-apache:
        container_name: php-apache
        build:
            context: .
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
            - ./config/vhosts:/etc/apache2/sites-enabled
            - ./logs/apache2:/var/log/apache2
        links:
            - mariadb
        environment:
            APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT}
            PMA_PORT: ${HOST_MACHINE_PMA_PORT}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
volumes:
    mariadb:
